import { useEffect, useMemo, useState } from 'react';
import Pagination from '../components/Pagination';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBoxOpen, faBuilding, faCalendarDays, faCheck, faChevronLeft, faChevronRight, faDownload, faEllipsisVertical, faEye, faFilter, faPlus, faPrint, faSearch, faUsers, faXmark } from '@fortawesome/free-solid-svg-icons';
import { cancelVoucher, downloadVoucherPdf, getCompanies, getVouchers } from '../services/api';

const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(value)) : 'Not provided';

export default function ApprovedVouchersPage() {
  const [filters, setFilters] = useState({ search: '', company: '', package: '', startDate: '', endDate: '' });
  const [page, setPage] = useState(1); const [data, setData] = useState(); const [all, setAll] = useState([]); const [companies, setCompanies] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = async () => { const query = { status: 'APPROVED', ...filters }; const [list, overview, companyData] = await Promise.all([getVouchers({ ...query, page, limit: 10 }), getVouchers({ status: 'APPROVED', limit: 100 }), getCompanies()]); setData(list); setAll(overview.vouchers || []); setCompanies(companyData.companies || []); };
  useEffect(() => { const timer = setTimeout(() => { setData(undefined); load().catch((e) => setError(e.message || 'Unable to load approved vouchers.')); }, 180); return () => clearTimeout(timer); }, [filters, page]);
  const set = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const clear = () => { setFilters({ search: '', company: '', package: '', startDate: '', endDate: '' }); setPage(1); };
  const download = async (voucher) => { try { setBusy(voucher._id); await downloadVoucherPdf(voucher._id, voucher.voucherNo); } catch (e) { setError(e.message || 'Unable to download PDF.'); } finally { setBusy(''); } };
  const print = (voucher) => window.open(`/admin/vouchers/${voucher._id}/preview?print=1`, '_blank', 'noopener,noreferrer');
  const cancel = async (voucher) => { if (!window.confirm(`Cancel voucher ${voucher.voucherNo}? It stays in history.`)) return; try { setBusy(voucher._id); await cancelVoucher(voucher._id); await load(); } catch (e) { setError(e.message || 'Unable to cancel voucher.'); } finally { setBusy(''); } };
  const packages = useMemo(() => [...new Set(all.map((v) => v.package).filter(Boolean))].sort(), [all]);
  const customers = useMemo(() => new Set(all.map((v) => v.customer?.name).filter(Boolean)).size, [all]);
  const pagination = data?.pagination || { page: 1, total: 0, limit: 10, totalPages: 1 };
  const from = pagination.total ? ((pagination.page - 1) * pagination.limit) + 1 : 0; const to = Math.min(pagination.page * pagination.limit, pagination.total);
  const pages = Array.from({ length: Math.min(pagination.totalPages, 5) }, (_, i) => (Math.max(1, Math.min(Math.max(1, pagination.totalPages - 4), pagination.page - 2)) + i));
  const metrics = [[faCheck, 'Approved Vouchers', data?.pagination.total || 0, 'green'], [faBuilding, 'Total Companies', companies.length, 'blue'], [faUsers, 'Total Customers', customers, 'blue'], [faBoxOpen, 'Total Packages', packages.length, 'purple']];
  return <section className="approved-reference">
    <header className="approved-heading"><div><div className="approved-breadcrumb"><span>Dashboard</span><i>›</i> Approved Vouchers</div><h1><FontAwesomeIcon icon={faCheck} /> Approved Vouchers</h1><p>View and manage all approved Umrah vouchers.</p></div><Link to="/admin/vouchers/new" className="approved-create"><FontAwesomeIcon icon={faPlus} /> Create Voucher</Link></header>
    {error && <div className="approved-error">{error}<button onClick={() => setError('')}><FontAwesomeIcon icon={faXmark} /></button></div>}
    <section className="approved-metrics">{metrics.map(([icon, label, value, color]) => <article key={label}><i className={color}><FontAwesomeIcon icon={icon} /></i><div><small>{label}</small><b>{value}</b><em><FontAwesomeIcon icon={faCheck} /> Live data</em></div></article>)}</section>
    <section className="approved-filters"><label className="approved-search"><FontAwesomeIcon icon={faSearch} /><input value={filters.search} onChange={(e) => set('search', e.target.value)} placeholder="Search by voucher no, customer, company..." /></label><label>Company<select value={filters.company} onChange={(e) => set('company', e.target.value)}><option value="">All Companies</option>{companies.map((item) => <option value={item._id} key={item._id}>{item.name}</option>)}</select></label><label>Package<select value={filters.package} onChange={(e) => set('package', e.target.value)}><option value="">All Packages</option>{packages.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label>Date Range<div className="approved-date"><FontAwesomeIcon icon={faCalendarDays} /><input type="date" value={filters.startDate} onChange={(e) => set('startDate', e.target.value)} /><span>–</span><input type="date" value={filters.endDate} onChange={(e) => set('endDate', e.target.value)} /></div></label><label>Status<span className="approved-status"><FontAwesomeIcon icon={faCheck} /> Approved</span></label><button className="approved-clear" onClick={clear}><FontAwesomeIcon icon={faFilter} /> Clear Filters</button></section>
    <section className="approved-table-card"><header><h2>Approved Vouchers</h2><span>Showing {from} to {to} of {pagination.total} vouchers</span></header><div className="approved-table-scroll"><table><thead><tr><th>#</th><th>Voucher No</th><th>Customer</th><th>Company</th><th>Package</th><th>Voucher Date</th><th>Status</th><th>Created By</th><th>Actions</th></tr></thead><tbody>{!data ? <tr><td colSpan="9" className="approved-empty">Loading approved vouchers...</td></tr> : data.vouchers.length ? data.vouchers.map((voucher, index) => <tr key={voucher._id}><td>{from + index}</td><td><Link className="approved-number" to={`/admin/vouchers/${voucher._id}/preview`}>{voucher.voucherNo}</Link></td><td><b>{voucher.customer?.name || 'Not provided'}</b><small>{voucher.mutamers?.[0]?.passportNo || 'No passport'}</small></td><td><div className="approved-company"><span>{voucher.company?.logo ? <img src={voucher.company.logo} alt="" /> : voucher.company?.name?.slice(0, 1) || 'U'}</span><div><b>{voucher.company?.name || 'Not provided'}</b><small>{voucher.company?.slug || 'company'}</small></div></div></td><td>{voucher.package || 'Not provided'}</td><td>{date(voucher.voucherDate)}</td><td><span className="approved-pill"><FontAwesomeIcon icon={faCheck} /> Approved</span></td><td><b>{voucher.createdBy?.name || 'Administrator'}</b><small>{voucher.createdBy?.role || 'admin'}</small></td><td><div className="approved-actions"><Link to={`/admin/vouchers/${voucher._id}/preview`} title="View voucher"><FontAwesomeIcon icon={faEye} /></Link><button title="Download PDF" disabled={busy === voucher._id} onClick={() => download(voucher)}><FontAwesomeIcon icon={faDownload} /></button><button title="Print voucher" onClick={() => print(voucher)}><FontAwesomeIcon icon={faPrint} /></button><details><summary title="More actions"><FontAwesomeIcon icon={faEllipsisVertical} /></summary><div><Link to={`/admin/vouchers/${voucher._id}/preview`}>Open Preview</Link><button disabled={busy === voucher._id} onClick={() => cancel(voucher)}>Cancel Voucher</button></div></details></div></td></tr>) : <tr><td colSpan="9" className="approved-empty"><b>No approved vouchers found.</b><span>Change filters or approve a draft voucher first.</span></td></tr>}</tbody></table></div><footer className="approved-pagination"><span>Showing {from} to {to} of {pagination.total} vouchers</span><Pagination page={pagination.page} totalPages={pagination.totalPages} onChange={setPage} /></footer></section>
  </section>;
}
