import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCalendarDays, faChevronLeft, faChevronRight, faDownload, faEye, faFilter, faSearch, faXmark } from '@fortawesome/free-solid-svg-icons';
import { getCompanies, getVouchers } from '../services/api';

const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(value)) : 'Not provided';
const csv = (value) => `"${String(value || '').replaceAll('"', '""')}"`;

export default function CancelledVouchersPage() {
  const [filters, setFilters] = useState({ search: '', company: '', startDate: '', endDate: '' });
  const [page, setPage] = useState(1); const [data, setData] = useState(); const [companies, setCompanies] = useState([]); const [all, setAll] = useState([]); const [error, setError] = useState('');
  const load = async () => { const query = { status: 'CANCELLED', ...filters }; const [list, allData, companyData] = await Promise.all([getVouchers({ ...query, page, limit: 10 }), getVouchers({ status: 'CANCELLED', limit: 100 }), getCompanies()]); setData(list); setAll(allData.vouchers || []); setCompanies(companyData.companies || []); };
  useEffect(() => { const timer = setTimeout(() => { setData(undefined); load().catch((e) => setError(e.message || 'Unable to load cancelled vouchers.')); }, 180); return () => clearTimeout(timer); }, [filters, page]);
  const set = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const clear = () => { setFilters({ search: '', company: '', startDate: '', endDate: '' }); setPage(1); };
  const exportRows = () => { const headings = ['Voucher No', 'Customer', 'Company', 'Package', 'Voucher Date', 'Cancelled Date', 'Reason', 'Cancelled By']; const rows = all.map((v) => [v.voucherNo, v.customer?.name, v.company?.name, v.package, date(v.voucherDate), date(v.cancelledAt || v.updatedAt), v.cancellationReason || 'Cancelled', v.cancelledBy?.name || v.createdBy?.name || 'Administrator']); const content = [headings, ...rows].map((row) => row.map(csv).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'cancelled-vouchers.csv'; link.click(); URL.revokeObjectURL(url); };
  const pagination = data?.pagination || { page: 1, total: 0, limit: 10, totalPages: 1 }; const from = pagination.total ? ((pagination.page - 1) * pagination.limit) + 1 : 0; const to = Math.min(pagination.page * pagination.limit, pagination.total); const pages = Array.from({ length: Math.min(pagination.totalPages, 5) }, (_, i) => (Math.max(1, Math.min(Math.max(1, pagination.totalPages - 4), pagination.page - 2)) + i));
  return <section className="cancelled-reference">
    <header className="cancelled-heading"><div><div className="cancelled-breadcrumb"><span>Dashboard</span><i>›</i> Cancelled Vouchers</div><h1><FontAwesomeIcon icon={faXmark} /> Cancelled Vouchers</h1><p>View and manage all cancelled Umrah vouchers. These vouchers are kept in the system for record purposes.</p></div><button className="cancelled-export" onClick={exportRows}><FontAwesomeIcon icon={faDownload} /> Export</button></header>
    {error && <div className="cancelled-error">{error}<button onClick={() => setError('')}><FontAwesomeIcon icon={faXmark} /></button></div>}
    <section className="cancelled-filters"><label className="cancelled-search"><FontAwesomeIcon icon={faSearch} /><input value={filters.search} onChange={(e) => set('search', e.target.value)} placeholder="Search by voucher no, customer, company..." /></label><label>Company<select value={filters.company} onChange={(e) => set('company', e.target.value)}><option value="">All Companies</option>{companies.map((item) => <option value={item._id} key={item._id}>{item.name}</option>)}</select></label><label>Date Range<div className="cancelled-date"><FontAwesomeIcon icon={faCalendarDays} /><input type="date" value={filters.startDate} onChange={(e) => set('startDate', e.target.value)} /><span>–</span><input type="date" value={filters.endDate} onChange={(e) => set('endDate', e.target.value)} /></div></label><label>Status<span className="cancelled-status"><FontAwesomeIcon icon={faXmark} /> Cancelled</span></label><button className="cancelled-clear" onClick={clear}><FontAwesomeIcon icon={faFilter} /> Clear Filters</button></section>
    <section className="cancelled-table-card"><header><h2>Cancelled Vouchers</h2><span>Showing {from} to {to} of {pagination.total} cancelled vouchers</span></header><div className="cancelled-table-scroll"><table><thead><tr><th>#</th><th>Voucher No</th><th>Customer</th><th>Company</th><th>Package</th><th>Voucher Date</th><th>Cancelled Date</th><th>Reason</th><th>Cancelled By</th><th>Actions</th></tr></thead><tbody>{!data ? <tr><td colSpan="10" className="cancelled-empty">Loading cancelled vouchers...</td></tr> : data.vouchers.length ? data.vouchers.map((voucher, index) => <tr key={voucher._id}><td>{from + index}</td><td><Link className="cancelled-number" to={`/admin/vouchers/${voucher._id}/preview`}>{voucher.voucherNo}</Link></td><td><b>{voucher.customer?.name || 'Not provided'}</b><small>{voucher.mutamers?.[0]?.passportNo || 'No passport'}</small></td><td><div className="cancelled-company"><span>{voucher.company?.logo ? <img src={voucher.company.logo} alt="" /> : voucher.company?.name?.slice(0, 1) || 'U'}</span><div><b>{voucher.company?.name || 'Not provided'}</b><small>{voucher.company?.slug || 'company'}</small></div></div></td><td>{voucher.package || 'Not provided'}</td><td>{date(voucher.voucherDate)}</td><td>{date(voucher.cancelledAt || voucher.updatedAt)}</td><td><span className="cancelled-reason">{voucher.cancellationReason || 'Cancelled'}</span></td><td><b>{voucher.cancelledBy?.name || voucher.createdBy?.name || 'Administrator'}</b><small>{voucher.cancelledBy?.role || voucher.createdBy?.role || 'admin'}</small></td><td><Link className="cancelled-view" to={`/admin/vouchers/${voucher._id}/preview`} title="View cancelled voucher"><FontAwesomeIcon icon={faEye} /></Link></td></tr>) : <tr><td colSpan="10" className="cancelled-empty"><b>No cancelled vouchers found.</b><span>Cancelled vouchers will appear here for history.</span></td></tr>}</tbody></table></div><footer className="cancelled-pagination"><span>Showing {from} to {to} of {pagination.total} cancelled vouchers</span><div><button disabled={pagination.page === 1} onClick={() => setPage(pagination.page - 1)}><FontAwesomeIcon icon={faChevronLeft} /></button>{pages.map((item) => <button key={item} className={item === pagination.page ? 'active' : ''} onClick={() => setPage(item)}>{item}</button>)}<button disabled={pagination.page === pagination.totalPages} onClick={() => setPage(pagination.page + 1)}><FontAwesomeIcon icon={faChevronRight} /></button></div></footer></section>
  </section>;
}
