import { useEffect, useMemo, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheck, faEye, faFilter, faPen, faSearch, faTrash, faUserGroup, faUsers, faXmark } from '@fortawesome/free-solid-svg-icons';
import { deleteCustomer, getCustomers, updateCustomer } from '../services/api';
import ImageUploadField from '../components/ImageUploadField';

const blank = { name: '', email: '', phone: '', familyHead: '', status: 'active', photo: '' };
const initials = (name) => name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'C';
const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Not provided';

export default function CustomersPage() {
  const [customers, setCustomers] = useState([]); const [filters, setFilters] = useState({ search: '', status: '', sort: 'newest' }); const [editor, setEditor] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { const result = await getCustomers(); setCustomers(result.customers || []); };
  useEffect(() => { load().catch((e) => setError(e.message || 'Unable to load customers.')); }, []);
  const visible = useMemo(() => customers.filter((customer) => `${customer.name} ${customer.email} ${customer.phone}`.toLowerCase().includes(filters.search.toLowerCase()) && (!filters.status || customer.status === filters.status)).sort((a, b) => filters.sort === 'oldest' ? new Date(a.lastActivity) - new Date(b.lastActivity) : new Date(b.lastActivity) - new Date(a.lastActivity)), [customers, filters]);
  const metrics = { total: customers.length, active: customers.filter((customer) => customer.status === 'active').length, inactive: customers.filter((customer) => customer.status === 'inactive').length, month: customers.filter((customer) => { const item = new Date(customer.lastActivity); const now = new Date(); return item.getMonth() === now.getMonth() && item.getFullYear() === now.getFullYear(); }).length };
  const open = (mode, customer = null) => setEditor({ mode, form: { name: customer.name, email: customer.email || '', phone: customer.phone || '', familyHead: customer.familyHead || '', status: customer.status, photo: customer.photo || '', _id: customer.id, totalVouchers: customer.totalVouchers, lastActivity: customer.lastActivity } });
  const set = (key, value) => setEditor((current) => ({ ...current, form: { ...current.form, [key]: value } }));
  const save = async (event) => { event.preventDefault(); if (editor.mode === 'view') return; try { setSaving(true); await updateCustomer(editor.form._id, editor.form); await load(); setEditor(null); } catch (e) { setError(e.message || 'Unable to save customer.'); } finally { setSaving(false); } };
  const remove = async (customer) => { if (!window.confirm(`Delete customer ${customer.name}?`)) return; try { await deleteCustomer(customer.id); await load(); if (editor?.form._id === customer.id) setEditor(null); } catch (e) { setError(e.message || 'Unable to delete customer.'); } };
  return <section className="customers-reference"><header className="customers-heading"><div><div><span>System Directory</span><i>›</i> Customers</div><h1><FontAwesomeIcon icon={faUsers} /> Customers</h1><p>Customers are added automatically when their voucher is created. View, edit or remove their details here.</p></div></header>{error && <div className="customers-error">{error}<button onClick={() => setError('')}><FontAwesomeIcon icon={faXmark} /></button></div>}
    <section className="customers-metrics"><Metric icon={faUsers} label="Total Customers" value={metrics.total} color="blue" note="All customer records" /><Metric icon={faCheck} label="Active Customers" value={metrics.active} color="green" note="Active customers" /><Metric icon={faXmark} label="Inactive Customers" value={metrics.inactive} color="red" note="Inactive customers" /><Metric icon={faUserGroup} label="New This Month" value={metrics.month} color="purple" note="Recent activity" /></section>
    <section className="customers-filters"><label><FontAwesomeIcon icon={faSearch} /><input value={filters.search} onChange={(e) => setFilters((current) => ({ ...current, search: e.target.value }))} placeholder="Search by name, email or phone..." /></label><select value={filters.status} onChange={(e) => setFilters((current) => ({ ...current, status: e.target.value }))}><option value="">All Status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select value={filters.sort} onChange={(e) => setFilters((current) => ({ ...current, sort: e.target.value }))}><option value="newest">Newest First</option><option value="oldest">Oldest First</option></select><button onClick={() => setFilters({ search: '', status: '', sort: 'newest' })}><FontAwesomeIcon icon={faFilter} /> Reset</button></section>
    <section className="customers-table-card"><div className="customers-table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Select customers" /></th><th>#</th><th>Customer Name</th><th>Email</th><th>Phone</th><th>Family Head</th><th>Total Vouchers</th><th>Status</th><th>Last Activity</th><th>Actions</th></tr></thead><tbody>{visible.map((customer, index) => <tr key={customer.id}><td><input type="checkbox" aria-label={`Select ${customer.name}`} /></td><td>{index + 1}</td><td><div className="customer-person"><span>{customer.photo ? <img src={customer.photo} alt="" /> : initials(customer.name)}</span><b>{customer.name}</b></div></td><td>{customer.email || 'Not provided'}</td><td>{customer.phone || 'Not provided'}</td><td>{customer.familyHead || 'Not provided'}</td><td>{customer.totalVouchers}</td><td><strong className={customer.status}>{customer.status}</strong></td><td>{date(customer.lastActivity)}</td><td><div className="customer-actions"><button onClick={() => open('view', customer)} title="View details"><FontAwesomeIcon icon={faEye} /></button><button onClick={() => open('edit', customer)} title="Edit customer"><FontAwesomeIcon icon={faPen} /></button><button onClick={() => remove(customer)} title="Delete customer"><FontAwesomeIcon icon={faTrash} /></button></div></td></tr>)}{!visible.length && <tr><td colSpan="10" className="customers-empty">No customers found. Create a voucher to add its customer automatically.</td></tr>}</tbody></table></div><footer>Showing {visible.length} of {customers.length} customers</footer></section>
    {editor && <div className="customer-modal-backdrop"><aside className="customer-editor"><header><div><span><FontAwesomeIcon icon={faUserGroup} /></span><div><h2>{editor.mode === 'create' ? 'Add New Customer' : editor.mode === 'edit' ? 'Edit Customer' : 'Customer Details'}</h2><p>{editor.mode === 'create' ? 'Fill in customer details to add a new record.' : 'View and manage customer details.'}</p></div></div><button type="button" onClick={() => setEditor(null)}><FontAwesomeIcon icon={faXmark} /></button></header><form onSubmit={save}>{editor.mode === 'view' && <div className="customer-summary"><span>{editor.form.photo ? <img src={editor.form.photo} alt="" /> : initials(editor.form.name)}</span><div><b>{editor.form.name}</b><em className={editor.form.status}>{editor.form.status}</em><small>{editor.form.totalVouchers} total vouchers · Last activity {date(editor.form.lastActivity)}</small></div></div>}<label>Customer Name <b>*</b><input disabled={editor.mode === 'view'} value={editor.form.name} onChange={(e) => set('name', e.target.value)} required placeholder="Enter customer name" /></label><label>Email<input disabled={editor.mode === 'view'} type="email" value={editor.form.email} onChange={(e) => set('email', e.target.value)} placeholder="customer@example.com" /></label><label>Phone Number<input disabled={editor.mode === 'view'} value={editor.form.phone} onChange={(e) => set('phone', e.target.value)} placeholder="+92 300 0000000" /></label><label>Family Head<input disabled={editor.mode === 'view'} value={editor.form.familyHead} onChange={(e) => set('familyHead', e.target.value)} placeholder="Family head name" /></label><label>Status<select disabled={editor.mode === 'view'} value={editor.form.status} onChange={(e) => set('status', e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{editor.mode !== 'view' && <ImageUploadField label="Customer Photo" folder="customers" value={editor.form.photo} onChange={(value) => set('photo', value)} help="PNG, JPG or WEBP • Max 5 MB" />}{editor.mode !== 'view' && <footer><button type="button" onClick={() => setEditor(null)}>Cancel</button><button className="save" disabled={saving}>{saving ? 'Saving...' : editor.mode === 'create' ? 'Save Customer' : 'Update Customer'}</button></footer>}</form></aside></div>}
  </section>;
}
function Metric({ icon, label, value, color, note }) { return <article><i className={color}><FontAwesomeIcon icon={icon} /></i><small>{label}</small><b>{value}</b><em>{note}</em></article>; }
