import { useEffect, useMemo, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBuilding, faChartBar, faFileLines, faSearch, faUserCircle, faUsers } from '@fortawesome/free-solid-svg-icons';
import { getVouchers } from '../services/api';

const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Not provided';
const statusClass = (status) => String(status || '').toLowerCase();

export default function DirectoryPage({ type }) {
  const [vouchers, setVouchers] = useState([]); const [query, setQuery] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getVouchers({ limit: 100 }).then((result) => setVouchers(result.vouchers || [])).catch((e) => setError(e.message || 'Unable to load data.')); }, []);
  const config = { agents: { icon: faUsers, title: 'Agents', description: 'Voucher creators and activity from your system.', empty: 'No agent activity found.' }, customers: { icon: faUserCircle, title: 'Customers', description: 'Customers collected from your voucher records.', empty: 'No customers found.' }, reports: { icon: faChartBar, title: 'Reports', description: 'Live voucher status summary and operational overview.', empty: 'No report data found.' } }[type];
  const agents = useMemo(() => Object.values(vouchers.reduce((result, voucher) => { const key = voucher.createdBy?._id || voucher.createdBy?.name || 'administrator'; if (!result[key]) result[key] = { name: voucher.createdBy?.name || 'Administrator', role: voucher.createdBy?.role || 'admin', total: 0, drafts: 0, approved: 0, cancelled: 0, updatedAt: voucher.updatedAt }; result[key].total += 1; result[key][String(voucher.status || '').toLowerCase()] += 1; return result; }, {})), [vouchers]);
  const customers = useMemo(() => Object.values(vouchers.reduce((result, voucher) => { const key = (voucher.customer?.name || '').trim().toLowerCase(); if (!key) return result; if (!result[key]) result[key] = { name: voucher.customer.name, familyHead: voucher.customer?.familyHead || 'Not provided', total: 0, latest: voucher.createdAt }; result[key].total += 1; if (new Date(voucher.createdAt) > new Date(result[key].latest)) result[key].latest = voucher.createdAt; return result; }, {})), [vouchers]);
  const matches = (value) => value.toLowerCase().includes(query.toLowerCase());
  const counts = ['DRAFT', 'APPROVED', 'CANCELLED', 'EXPIRED'].map((status) => [status, vouchers.filter((voucher) => voucher.status === status).length]);
  if (error) return <div className="directory-error">{error}</div>;
  return <section className="directory-page"><header><div><small>SYSTEM DIRECTORY</small><h1><FontAwesomeIcon icon={config.icon} /> {config.title}</h1><p>{config.description}</p></div></header>{type !== 'reports' && <label className="directory-search"><FontAwesomeIcon icon={faSearch} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={type === 'agents' ? 'Search agents...' : 'Search customers...'} /></label>}{type === 'agents' && <section className="directory-card"><table><thead><tr><th>Agent</th><th>Role</th><th>Total Vouchers</th><th>Draft</th><th>Approved</th><th>Cancelled</th><th>Last Activity</th></tr></thead><tbody>{agents.filter((item) => matches(item.name)).map((item) => <tr key={item.name}><td><span className="directory-avatar">{item.name.slice(0, 1)}</span><b>{item.name}</b></td><td>{item.role}</td><td>{item.total}</td><td>{item.drafts}</td><td>{item.approved}</td><td>{item.cancelled}</td><td>{date(item.updatedAt)}</td></tr>)}</tbody></table>{!agents.length && <Empty text={config.empty} />}</section>}{type === 'customers' && <section className="directory-card"><table><thead><tr><th>Customer</th><th>Family Head</th><th>Total Vouchers</th><th>Last Voucher</th></tr></thead><tbody>{customers.filter((item) => matches(item.name)).map((item) => <tr key={item.name}><td><span className="directory-avatar"><FontAwesomeIcon icon={faUserCircle} /></span><b>{item.name}</b></td><td>{item.familyHead}</td><td>{item.total}</td><td>{date(item.latest)}</td></tr>)}</tbody></table>{!customers.length && <Empty text={config.empty} />}</section>}{type === 'reports' && <><section className="report-cards">{counts.map(([status, total]) => <article key={status} className={statusClass(status)}><span>{status}</span><b>{total}</b><small>Vouchers</small></article>)}</section><section className="directory-card report-table"><h2><FontAwesomeIcon icon={faFileLines} /> Recent Voucher Activity</h2><table><thead><tr><th>Voucher No</th><th>Customer</th><th>Company</th><th>Status</th><th>Updated</th></tr></thead><tbody>{vouchers.slice(0, 12).map((voucher) => <tr key={voucher._id}><td><b>{voucher.voucherNo}</b></td><td>{voucher.customer?.name || 'Not provided'}</td><td>{voucher.company?.name || 'Not provided'}</td><td><span className={`directory-status ${statusClass(voucher.status)}`}>{voucher.status}</span></td><td>{date(voucher.updatedAt)}</td></tr>)}</tbody></table>{!vouchers.length && <Empty text={config.empty} />}</section></>}</section>;
}
function Empty({ text }) { return <p className="directory-empty">{text}</p>; }
