import { useEffect, useMemo, useState } from 'react';
import Pagination from '../components/Pagination';
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBuilding, faCalendarDays, faCheck, faClock, faEye, faFileLines, faFilter, faPen, faPlus, faSearch, faTrash, faUser, faXmark } from '@fortawesome/free-solid-svg-icons';
import { approveVoucher, deleteVoucher, getCompanies, getVouchers } from '../services/api';

const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(value)) : 'Not provided';
const time = (value) => value ? new Intl.DateTimeFormat('en-US', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '';

export default function DraftVouchersPage() {
  const [filters, setFilters] = useState({ search: '', company: '', package: '', startDate: '', endDate: '' });
  const [page, setPage] = useState(1); const [data, setData] = useState(); const [all, setAll] = useState([]); const [companies, setCompanies] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = async () => { const query = { status: 'DRAFT', ...filters }; const [list, overview, companyData] = await Promise.all([getVouchers({ ...query, page, limit: 10 }), getVouchers({ status: 'DRAFT', limit: 100 }), getCompanies()]); setData(list); setAll(overview.vouchers || []); setCompanies(companyData.companies || []); };
  useEffect(() => { const timer = setTimeout(() => { setData(undefined); load().catch((e) => setError(e.message || 'Unable to load draft vouchers.')); }, 180); return () => clearTimeout(timer); }, [filters, page]);
  const set = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const reset = () => { setFilters({ search: '', company: '', package: '', startDate: '', endDate: '' }); setPage(1); };
  const remove = async (voucher) => { if (!window.confirm(`Delete draft ${voucher.voucherNo}? This cannot be undone.`)) return; try { setBusy(voucher._id); await deleteVoucher(voucher._id); await load(); } catch (e) { setError(e.message || 'Unable to delete draft voucher.'); } finally { setBusy(''); } };
  const approve = async (voucher) => { if (!window.confirm('Approve this voucher?')) return; try { setBusy(voucher._id); await approveVoucher(voucher._id); await load(); } catch (e) { setError(e.message || 'Unable to approve draft voucher.'); } finally { setBusy(''); } };
  const packages = useMemo(() => [...new Set(all.map((v) => v.package).filter(Boolean))].sort(), [all]);
  const agents = useMemo(() => new Set(all.map((v) => v.createdBy?.name).filter(Boolean)).size, [all]);
  const month = useMemo(() => { const now = new Date(); return all.filter((v) => { const created = new Date(v.createdAt); return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear(); }).length; }, [all]);
  const latest = useMemo(() => all.slice().sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt))[0], [all]);
  const pagination = data?.pagination || { page: 1, total: 0, limit: 10, totalPages: 1 }; const from = pagination.total ? ((pagination.page - 1) * pagination.limit) + 1 : 0; const to = Math.min(pagination.page * pagination.limit, pagination.total); const pages = Array.from({ length: Math.min(pagination.totalPages, 5) }, (_, i) => (Math.max(1, Math.min(Math.max(1, pagination.totalPages - 4), pagination.page - 2)) + i));
  const cards = [[faFileLines, 'Total Draft Vouchers', data?.pagination.total || 0, 'blue', 'Pending approval'], [faCalendarDays, 'This Month', month, 'green', 'Created this month'], [faBuilding, 'Companies', companies.length, 'purple', 'Active companies'], [faUser, 'Agents', agents, 'orange', 'Created by users'], [faClock, 'Last Updated', latest ? date(latest.updatedAt) : '—', 'red', latest ? time(latest.updatedAt) : 'No drafts']];
  return <section className="draft-reference">
    <header className="draft-heading"><div><small>VOUCHERS</small><h1><FontAwesomeIcon icon={faFileLines} /> Draft Voucher</h1><p>Manage and review your draft vouchers before final submission.</p></div><Link to="/admin/vouchers/new" className="draft-create"><FontAwesomeIcon icon={faPlus} /> Create Voucher</Link></header>
    {error && <div className="draft-error">{error}<button onClick={() => setError('')}><FontAwesomeIcon icon={faXmark} /></button></div>}
    <section className="draft-metrics">{cards.map(([icon, label, value, color, note]) => <article key={label}><i className={color}><FontAwesomeIcon icon={icon} /></i><small>{label}</small><b>{value}</b><em>{note}</em></article>)}</section>
    <div className="draft-layout"><section className="draft-table-card"><header><h2>Draft Voucher List</h2><span>Showing {from}–{to} of {pagination.total}</span></header><div className="draft-table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Select all drafts" /></th><th>Voucher No.</th><th>Company</th><th>Agent</th><th>Customer</th><th>Package</th><th>Created On</th><th>Status</th><th>Actions</th></tr></thead><tbody>{!data ? <tr><td colSpan="9" className="draft-empty">Loading draft vouchers...</td></tr> : data.vouchers.length ? data.vouchers.map((voucher) => <tr key={voucher._id}><td><input type="checkbox" aria-label={`Select ${voucher.voucherNo}`} /></td><td><Link to={`/admin/vouchers/${voucher._id}/preview?edit=1`}><b>{voucher.voucherNo}</b><small>Draft</small></Link></td><td><b>{voucher.company?.name || 'Not provided'}</b><small>{voucher.company?.slug || 'company'}</small></td><td><b>{voucher.createdBy?.name || 'Administrator'}</b><small>{voucher.createdBy?.role || 'admin'}</small></td><td><b>{voucher.customer?.name || 'Not provided'}</b><small>{voucher.mutamers?.[0]?.passportNo || 'No passport'}</small></td><td><b>{voucher.package || 'Not provided'}</b><small>{voucher.travelBy || 'Travel not set'}</small></td><td><b>{date(voucher.createdAt)}</b><small>{time(voucher.createdAt)}</small></td><td><span className="draft-pill">Draft</span></td><td><div className="draft-actions"><button className="approve" disabled={busy === voucher._id} onClick={() => approve(voucher)} title="Approve voucher"><FontAwesomeIcon icon={faCheck} /></button><Link to={`/admin/vouchers/${voucher._id}/preview`} title="View draft"><FontAwesomeIcon icon={faEye} /></Link><Link to={`/admin/vouchers/${voucher._id}/preview?edit=1`} title="Edit draft"><FontAwesomeIcon icon={faPen} /></Link><button disabled={busy === voucher._id} onClick={() => remove(voucher)} title="Delete draft"><FontAwesomeIcon icon={faTrash} /></button></div></td></tr>) : <tr><td colSpan="9" className="draft-empty"><b>No draft vouchers found.</b><span>Create a voucher to see it here.</span></td></tr>}</tbody></table></div><footer className="draft-pagination"><Pagination page={pagination.page} totalPages={pagination.totalPages} onChange={setPage} /></footer></section>
      <aside className="draft-filter"><h2><FontAwesomeIcon icon={faFilter} /> Filter</h2><label>Search<input value={filters.search} onChange={(e) => set('search', e.target.value)} placeholder="Voucher No, Company, Customer..." /></label><label>Company<select value={filters.company} onChange={(e) => set('company', e.target.value)}><option value="">All Companies</option>{companies.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label>Package<select value={filters.package} onChange={(e) => set('package', e.target.value)}><option value="">All Packages</option>{packages.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Date Range<input type="date" value={filters.startDate} onChange={(e) => set('startDate', e.target.value)} /><input type="date" value={filters.endDate} onChange={(e) => set('endDate', e.target.value)} /></label><label>Status<select disabled><option>Draft</option></select></label><footer><button onClick={reset}>Reset</button><button className="apply" onClick={load}>Apply</button></footer></aside>
    </div>
  </section>;
}
