import { useState } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
export default function LoginPage() {
  const { user, signIn } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  if (user) return <Navigate to="/admin" replace />;
  const submit = async (event) => { event.preventDefault(); setError(''); setSubmitting(true); try { await signIn(email, password); navigate(location.state?.from?.pathname || '/admin', { replace: true }); } catch (requestError) { setError(requestError.message); } finally { setSubmitting(false); } };
  return <main className="grid min-h-screen bg-slate-950 lg:grid-cols-2"><section className="hidden bg-gradient-to-br from-blue-700 via-blue-900 to-slate-950 p-14 lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3 text-white"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-400 text-lg font-black text-slate-900">U</span><span className="text-lg font-bold">Umrah Voucher</span></div><div><p className="text-sm font-bold tracking-[0.2em] text-orange-300">OPERATIONS PLATFORM</p><h1 className="mt-5 max-w-lg text-5xl font-bold leading-tight text-white">Manage every Umrah journey with confidence.</h1><p className="mt-6 max-w-md text-lg leading-8 text-blue-100">Create secure, branded vouchers and make verification effortless.</p></div><p className="text-sm text-blue-200">Secure access for authorized travel operations teams.</p></section><section className="flex items-center justify-center p-6 sm:p-10"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-800 bg-white p-7 shadow-2xl sm:p-9"><div className="mb-8 lg:hidden"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-400 font-black text-slate-900">U</span></div><p className="text-sm font-semibold text-blue-700">WELCOME BACK</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Sign in to your account</h1><p className="mt-2 text-sm text-slate-500">Use authorized admin or staff credentials.</p>{error && <p role="alert" className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mt-7 block text-sm font-semibold text-slate-700">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 outline-none ring-blue-500 focus:ring-2" placeholder="you@company.com" /></label><label className="mt-5 block text-sm font-semibold text-slate-700">Password<input required minLength="8" type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 outline-none ring-blue-500 focus:ring-2" placeholder="Enter your password" /></label><button disabled={submitting} className="mt-7 w-full rounded-lg bg-blue-700 px-4 py-3 font-semibold text-white hover:bg-blue-800 disabled:opacity-60">{submitting ? 'Signing in...' : 'Sign in'}</button></form></section></main>;
}
