import { useEffect, useState } from 'react';
import Pagination from '../components/Pagination';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheck, faChevronLeft, faChevronRight, faEnvelope, faGear, faKey, faPen, faPlus, faShieldHalved, faTrash, faUser, faUserGear, faUsers, faXmark } from '@fortawesome/free-solid-svg-icons';
import { useAuth } from '../context/AuthContext';
import { createSettingsAdmin, deleteSettingsAdmin, getDashboardBranding, getSettingsAdmins, updateDashboardBranding, updateSettingsAdmin, updateSettingsProfile } from '../services/api';
import ImageUploadField from '../components/ImageUploadField';

const emptyAdmin = { name: '', email: '', password: '', role: 'admin', status: 'active', profilePhoto: '' };
const defaultBranding = { dashboardName: 'Umrah Voucher', dashboardSubtitle: 'Management System', logoUrl: '', sidebarColor: '#061c40', sidebarTextColor: '#d4e4fc', appTextColor: '#112e59' };
const initials = (name) => name?.slice(0, 1).toUpperCase() || 'A';
const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : 'Not available';

export default function SettingsPage() {
  const { user, setCurrentUser } = useAuth();
  const [tab, setTab] = useState('admins');
  const [admins, setAdmins] = useState([]); const [adminPage, setAdminPage] = useState(1);
  const [admin, setAdmin] = useState(emptyAdmin);
  const [editing, setEditing] = useState('');
  const [profile, setProfile] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const [branding, setBranding] = useState(defaultBranding);
  const [notice, setNotice] = useState('');
  const [saving, setSaving] = useState(false);

  const load = async () => { try { const data = await getSettingsAdmins(); setAdmins(data.admins || []); const current = (data.admins || []).find((item) => item.id === user?.id); if (current && current.role !== user?.role) setCurrentUser(current); } catch (error) { setNotice(error.message || 'Unable to load administrators.'); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { setProfile({ name: user?.name || '', email: user?.email || '', password: '', confirmPassword: '', profilePhoto: user?.profilePhoto || '' }); }, [user]); useEffect(() => { getDashboardBranding().then((data) => setBranding({ ...defaultBranding, ...(data.branding || {}) })).catch((error) => setNotice(error.message || 'Unable to load dashboard settings.')); }, []);
  const adminPageSize = 10; const adminTotalPages = Math.max(1, Math.ceil(admins.length / adminPageSize)); const currentAdminPage = Math.min(adminPage, adminTotalPages); const pagedAdmins = admins.slice((currentAdminPage - 1) * adminPageSize, currentAdminPage * adminPageSize); const adminPages = Array.from({ length: Math.min(adminTotalPages, 5) }, (_, index) => index + 1); const field = (key, value) => setAdmin((current) => ({ ...current, [key]: value }));
  const profileField = (key, value) => setProfile((current) => ({ ...current, [key]: value })); const brandingField = (key, value) => setBranding((current) => ({ ...current, [key]: value }));
  const startAdd = () => { setEditing(''); setAdmin(emptyAdmin); document.getElementById('admin-form')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
  const startEdit = (item) => { setEditing(item.id); setAdmin({ name: item.name || '', email: item.email || '', password: '', role: item.role || 'admin', status: item.status || 'active', profilePhoto: item.profilePhoto || '' }); document.getElementById('admin-form')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
  const saveAdmin = async (event) => { event.preventDefault(); try { setSaving(true); if (editing) await updateSettingsAdmin(editing, admin); else await createSettingsAdmin(admin); setNotice(editing ? 'Administrator updated successfully.' : 'Administrator added successfully.'); setAdmin(emptyAdmin); setEditing(''); await load(); } catch (error) { setNotice(error.message || 'Unable to save administrator.'); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm('Delete administrator ' + item.name + '?')) return; try { await deleteSettingsAdmin(item.id); setNotice('Administrator deleted successfully.'); await load(); } catch (error) { setNotice(error.message || 'Unable to delete administrator.'); } };
  const saveProfile = async (event) => { event.preventDefault(); if (profile.password !== profile.confirmPassword) return setNotice('New password and confirm password must match.'); try { setSaving(true); const data = await updateSettingsProfile({ name: profile.name, email: profile.email, password: profile.password, profilePhoto: profile.profilePhoto }); setCurrentUser(data.user); setProfile((current) => ({ ...current, password: '', confirmPassword: '' })); setNotice('Profile updated successfully.'); } catch (error) { setNotice(error.message || 'Unable to update profile.'); } finally { setSaving(false); } }; const saveBranding = async (event) => { event.preventDefault(); try { setSaving(true); const data = await updateDashboardBranding(branding); setBranding({ ...defaultBranding, ...(data.branding || {}) }); setNotice('Dashboard configuration saved successfully. Refresh any open dashboard pages to see the new branding.'); } catch (error) { setNotice(error.message || 'Unable to save dashboard configuration.'); } finally { setSaving(false); } };

  return <section className="settings-reference">
    <header className="settings-heading"><div><div><span>Dashboard</span> Settings</div><h1><FontAwesomeIcon icon={faGear} /> System Settings</h1><p>Manage admin accounts, update your profile and system configuration.</p></div></header>
    {notice && <div className="settings-notice">{notice}<button onClick={() => setNotice('')}><FontAwesomeIcon icon={faXmark} /></button></div>}
    <nav className="settings-tabs"><button className={tab === 'admins' ? 'active' : ''} onClick={() => setTab('admins')}><FontAwesomeIcon icon={faUsers} /> Admin Management</button><button className={tab === 'profile' ? 'active' : ''} onClick={() => setTab('profile')}><FontAwesomeIcon icon={faUser} /> My Profile</button><button className={tab === 'configuration' ? 'active' : ''} onClick={() => setTab('configuration')}><FontAwesomeIcon icon={faGear} /> System Configuration</button></nav>
    <div className="settings-tab-content">
      {tab === 'admins' && <><section className="settings-card admin-card"><header><div><span><FontAwesomeIcon icon={faUsers} /></span><div><h2>Admin Management</h2><p>View, edit or remove system administrator accounts.</p></div></div><button className="settings-primary" onClick={startAdd}><FontAwesomeIcon icon={faPlus} /> Add Admin</button></header><div className="settings-table-scroll"><table><thead><tr><th>#</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>{pagedAdmins.map((item, index) => <tr key={item.id}><td>{((currentAdminPage - 1) * adminPageSize) + index + 1}</td><td><span className="settings-avatar">{item.profilePhoto ? <img src={item.profilePhoto} alt="" /> : initials(item.name)}</span><b>{item.name}</b></td><td>{item.email}</td><td><em className="super">{item.role === 'super_admin' ? 'Super Admin' : 'Admin'}</em></td><td><em className={item.status === 'inactive' ? 'inactive' : 'active'}>{item.status === 'inactive' ? 'Inactive' : 'Active'}</em></td><td>{date(item.lastLogin)}</td><td><button title="Edit admin" onClick={() => startEdit(item)}><FontAwesomeIcon icon={faPen} /></button><button className="danger" title="Delete admin" onClick={() => remove(item)}><FontAwesomeIcon icon={faTrash} /></button></td></tr>)}{!admins.length && <tr><td colSpan="7" className="settings-empty">No administrator accounts found.</td></tr>}</tbody></table></div><footer>Showing {admins.length ? ((currentAdminPage - 1) * adminPageSize) + 1 : 0} to {Math.min(currentAdminPage * adminPageSize, admins.length)} of {admins.length} admins <Pagination page={currentAdminPage} totalPages={adminTotalPages} onChange={setAdminPage} /></footer></section>
      <form id="admin-form" className="settings-card add-admin-card" onSubmit={saveAdmin}><header><div><span><FontAwesomeIcon icon={faUserGear} /></span><div><h2>{editing ? 'Edit Admin' : 'Add New Admin'}</h2><p>{editing ? 'Update administrator credentials and status.' : 'Create a new administrator account with full access.'}</p></div></div></header><div className="settings-add-fields"><label>Username <b>*</b><input value={admin.name} onChange={(event) => field('name', event.target.value)} placeholder="Enter username" required /></label><label>Email <b>*</b><input type="email" value={admin.email} onChange={(event) => field('email', event.target.value)} placeholder="Enter email address" required /></label><label>{editing ? 'New Password' : 'Password'} {!editing && <b>*</b>}<input type="password" value={admin.password} onChange={(event) => field('password', event.target.value)} placeholder={editing ? 'Leave blank to keep password' : 'Minimum 8 characters'} required={!editing} minLength={editing ? undefined : 8} /></label><label>Role <b>*</b><select value={admin.role} disabled><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select></label><label>Status<select value={admin.status} onChange={(event) => field('status', event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><ImageUploadField label="Profile Photo" folder="admins" value={admin.profilePhoto} onChange={(value) => field('profilePhoto', value)} help="PNG, JPG or WEBP - shown with this admin profile" /></div><footer><button type="button" onClick={() => { setEditing(''); setAdmin(emptyAdmin); }}>Cancel</button><button className="settings-primary" disabled={saving}><FontAwesomeIcon icon={faCheck} /> {saving ? 'Saving...' : editing ? 'Update Admin' : 'Save Admin'}</button></footer></form></>}
      {tab === 'profile' && <ProfileCard profile={profile} field={profileField} onSave={saveProfile} saving={saving} />}
      {tab === 'configuration' && <section className="settings-card configuration-card"><header><div><span><FontAwesomeIcon icon={faGear} /></span><div><h2>Dashboard Configuration</h2><p>Control the dashboard logo, names and dashboard colors.</p></div></div></header><form className="dashboard-branding-form" onSubmit={saveBranding}><div className="dashboard-branding-grid"><ImageUploadField label="Dashboard Logo" folder="dashboard" value={branding.logoUrl} onChange={(value) => brandingField('logoUrl', value)} help="PNG, JPG or WEBP - shown in the sidebar" /><label>Dashboard Name<input value={branding.dashboardName} onChange={(event) => brandingField('dashboardName', event.target.value)} required maxLength="100" placeholder="Umrah Voucher" /></label><label>Dashboard Subtitle<input value={branding.dashboardSubtitle} onChange={(event) => brandingField('dashboardSubtitle', event.target.value)} maxLength="100" placeholder="Management System" /></label><label>Sidebar Color<input type="color" value={branding.sidebarColor} onChange={(event) => brandingField('sidebarColor', event.target.value)} /><small>{branding.sidebarColor}</small></label><label>Sidebar Font Color<input type="color" value={branding.sidebarTextColor} onChange={(event) => brandingField('sidebarTextColor', event.target.value)} /><small>{branding.sidebarTextColor}</small></label><label>Dashboard Font Color<input type="color" value={branding.appTextColor} onChange={(event) => brandingField('appTextColor', event.target.value)} /><small>{branding.appTextColor}</small></label></div><footer><button type="button" onClick={() => setBranding(defaultBranding)}>Reset</button><button className="settings-primary" disabled={saving}><FontAwesomeIcon icon={faCheck} /> {saving ? 'Saving...' : 'Save Dashboard Settings'}</button></footer></form></section>}
    </div>
    <section className="settings-card security-card"><header><div><span><FontAwesomeIcon icon={faShieldHalved} /></span><div><h2>Security & Access</h2><p>Open a section to manage administrator security.</p></div></div></header><button onClick={() => setTab('admins')}><FontAwesomeIcon icon={faUsers} /> Add / Edit / Delete Admins</button><button onClick={() => setTab('configuration')}><FontAwesomeIcon icon={faShieldHalved} /> Manage Roles & Permissions</button><button onClick={() => setTab('profile')}><FontAwesomeIcon icon={faKey} /> Change Password</button><button onClick={() => setTab('profile')}><FontAwesomeIcon icon={faEnvelope} /> Change Email</button></section>
  </section>;
}
function ProfileCard({ profile, field, onSave, saving }) { return <section className="settings-card profile-full"><header><div><span><FontAwesomeIcon icon={faUser} /></span><div><h2>My Profile</h2><p>Update your profile image, username, email and password.</p></div></div></header><form className="settings-profile-form" onSubmit={onSave}><div className="profile-identity"><span>{profile.profilePhoto ? <img src={profile.profilePhoto} alt="" /> : initials(profile.name)}</span><b>{profile.name || 'Administrator'}</b></div><ImageUploadField label="Profile Photo" folder="admins" value={profile.profilePhoto} onChange={(value) => field('profilePhoto', value)} help="PNG, JPG or WEBP - shown in your profile and header" /><label>Username <b>*</b><input value={profile.name} onChange={(event) => field('name', event.target.value)} required /></label><label>Email <b>*</b><input type="email" value={profile.email} onChange={(event) => field('email', event.target.value)} required /></label><label>New Password<input type="password" value={profile.password} onChange={(event) => field('password', event.target.value)} placeholder="Leave blank if you don't want to change" /></label><label>Confirm Password<input type="password" value={profile.confirmPassword} onChange={(event) => field('confirmPassword', event.target.value)} placeholder="Leave blank if you don't want to change" /></label><button className="settings-primary" disabled={saving}><FontAwesomeIcon icon={faCheck} /> {saving ? 'Saving...' : 'Update Profile'}</button></form></section>; }