import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBed, faCalendarDays, faEnvelope, faPhone, faQrcode, faTicket, faUser, faUsers } from '@fortawesome/free-solid-svg-icons';
import { faWhatsapp } from '@fortawesome/free-brands-svg-icons';

const value = (item, fallback = 'Not provided') => item || fallback;
const date = (item) => item ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(item)) : 'Not provided';
const statusLabel = (status) => String(status || 'DRAFT').toLowerCase();

function DocumentTable({ title, rows, columns }) {
  return <section className="document-table-section"><h3>{title}</h3>{rows?.length ? <div className="document-table-scroll"><table><thead><tr><th>#</th>{columns.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td>{index + 1}</td>{columns.map(([key]) => <td key={key}>{['date', 'travelDate', 'checkIn', 'checkOut'].includes(key) ? date(row[key]) : value(row[key], '—')}</td>)}</tr>)}</tbody></table></div> : <p className="document-empty">No {title.toLowerCase()} recorded.</p>}</section>;
}

function ManagementContacts({ blocks, contacts = {} }) {
  const legacy = [['Makkah Management', contacts.makkah], ['Madinah Management', contacts.madinah], ['Transport Management', contacts.transport]].map(([title, contact]) => ({ title, lines: [contact?.name, contact?.phone].filter(Boolean) }));
  const items = blocks?.length ? blocks : legacy.filter((item) => item.lines.length);
  return items.length ? <div className="document-management-contacts">{items.map((block, index) => <section key={`${block.title}-${index}`}><b>{block.title || 'Management Contact'}</b>{block.lines?.filter(Boolean).map((line, lineIndex) => <span key={lineIndex}>{line}</span>)}</section>)}</div> : null;
}

export default function VoucherDocument({ voucher, qrCode, className = '' }) {
  const company = voucher.company || {};
  const header = voucher.voucherHeader || {};
  const totalPax = voucher.totalPax ?? ((Number(voucher.adultCount) || 0) + (Number(voucher.childCount) || 0) + (Number(voucher.infantCount) || 0));
  const totalNights = voucher.totalNights ?? (voucher.accommodation || []).reduce((total, item) => total + (Number(item.nights) || 0), 0);
  return <article className={`voucher-document ${voucher.watermarkUrl ? 'has-watermark' : ''} ${className}`} style={voucher.watermarkUrl ? { '--voucher-watermark': `url("${voucher.watermarkUrl}")` } : undefined}>
    <header className="document-header"><div className="document-brand"><div className="document-logo">{company.logo ? <img src={company.logo} alt={`${company.name} logo`} /> : <FontAwesomeIcon icon={faTicket} />}</div><div><b>{company.name || 'Umrah Voucher'}</b><small>Umrah & Hajj Services</small><span><FontAwesomeIcon icon={faPhone} /> Phone: {value(company.phone, 'Not provided')}</span>{company.whatsapp && <span><FontAwesomeIcon icon={faWhatsapp} /> WhatsApp: {company.whatsapp}</span>}<span><FontAwesomeIcon icon={faEnvelope} /> Email: {value(company.email, 'Not provided')}</span></div></div>{(header.rightLogo || header.rightTitle || header.rightSubtitle || header.rightContact) && <div className="document-partner">{header.rightLogo && <img src={header.rightLogo} alt="Partner logo" />}<div>{header.rightTitle && <b>{header.rightTitle}</b>}{header.rightSubtitle && <small>{header.rightSubtitle}</small>}{header.rightContact && <span>{header.rightContact}</span>}</div></div>}<em className={`document-status ${statusLabel(voucher.status)}`}>{voucher.status || 'DRAFT'}</em><div className="document-title"><h1>UMRAH VOUCHER</h1><p>Your Journey to a Blessed Life</p></div></header>
    {voucher.status === 'CANCELLED' || voucher.status === 'EXPIRED' ? <div className="document-invalid">INVALID VOUCHER — This voucher is {String(voucher.status).toLowerCase()}.</div> : null}
    <section className="document-facts">{[[faTicket, 'Voucher No', voucher.voucherNo], [faTicket, 'Booking No', voucher.bookingNo], [faCalendarDays, 'Voucher Date', date(voucher.voucherDate)], [faBed, 'Package', voucher.package], [faTicket, 'Status', voucher.status]].map(([icon, label, item]) => <div key={label}><FontAwesomeIcon icon={icon} /><span><small>{label}</small><b>{value(item)}</b></span></div>)}</section>
    <section className="document-customer"><h3><FontAwesomeIcon icon={faUsers} /> Customer / Family Information</h3><div><span><FontAwesomeIcon icon={faUser} /><small>Customer Name</small><b>{value(voucher.customer?.name)}</b></span><span><FontAwesomeIcon icon={faUser} /><small>Family Head</small><b>{value(voucher.customer?.familyHead)}</b></span><span><FontAwesomeIcon icon={faUser} /><small>Phone</small><b>{value(voucher.customer?.phone)}</b></span><span><FontAwesomeIcon icon={faUser} /><small>Email</small><b>{value(voucher.customer?.email)}</b></span></div></section>
    <section className="document-group"><div><small>Manual / Service No</small><b>{value(voucher.manualServiceNo)}</b></div><div><small>Branch</small><b>{value(voucher.branch)}</b></div><div><small>Group No</small><b>{value(voucher.groupNo)}</b></div><div><small>Group Name</small><b>{value(voucher.groupName)}</b></div><div><small>Adult / Child / Infant</small><b>{Number(voucher.adultCount) || 0} / {Number(voucher.childCount) || 0} / {Number(voucher.infantCount) || 0}</b></div><div><small>Total Pax</small><b>{totalPax}</b></div><div><small>Separate Beds</small><b>{Number(voucher.separateBeds) || 0}</b></div><div><small>Total Nights</small><b>{totalNights}</b></div></section>
    <DocumentTable title="Mutamers / Guests" rows={voucher.mutamers} columns={[['name', 'Name'], ['passportNo', 'Passport No'], ['gender', 'Gender'], ['paxType', 'Pax Type'], ['bedType', 'Bed Type'], ['visaNo', 'Visa No'], ['ticketNo', 'Ticket No'], ['pnr', 'PNR']]} />
    <div className="document-two-columns"><DocumentTable title="Accommodation" rows={voucher.accommodation} columns={[['city', 'City'], ['hotelName', 'Hotel'], ['roomType', 'Room'], ['mealPlan', 'Meal'], ['checkIn', 'Check In'], ['checkOut', 'Check Out'], ['nights', 'Nights']]} /><DocumentTable title="Flights" rows={voucher.flights} columns={[['leg', 'Leg'], ['flightNo', 'Flight'], ['sector', 'Sector'], ['date', 'Date'], ['etd', 'ETD'], ['eta', 'ETA']]} /></div>
    <div className="document-two-columns"><DocumentTable title="Transport / Services" rows={voucher.transport} columns={[['travelDate', 'Date'], ['transporter', 'Transporter'], ['transportType', 'Type'], ['route', 'Route']]} /><section className="document-terms"><h3>Terms & Conditions</h3>{voucher.termsAndConditions?.length ? <ol>{voucher.termsAndConditions.map((term, index) => <li key={index}>{term}</li>)}</ol> : <p className="document-empty">No terms recorded.</p>}</section></div>
    {voucher.specialInstructions && <section className="document-instructions"><b>Special Instructions</b><p>{voucher.specialInstructions}</p></section>}
    <footer className="document-footer"><ManagementContacts blocks={voucher.contactBlocks} contacts={voucher.managementContacts} />{qrCode && <div className="document-qr"><img src={qrCode} alt="Secure voucher QR code" /><small><FontAwesomeIcon icon={faQrcode} /> Scan to open voucher</small></div>}</footer><div className="document-bottom">{company.name || 'Umrah Voucher Management'} <span>•</span> Making Your Umrah Journey Easier</div>
  </article>;
}
